# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.18.4

# Mod Properties
mod_version=1.3.4
maven_group=com.red.masaadditions
archives_base_name=masaadditions

# Dependencies
tweakeroo_fileid=6960682
minihud_fileid=6960677
litematica_fileid=6960673
malilib_fileid=6960657
masa_minecraft_version=1.21.8
fabric_version=0.136.1+1.21.8