# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.15.11

# Mod Properties
mod_version=1.2.0
maven_group=com.red.masaadditions
archives_base_name=masaadditions

# Dependencies
masa_minecraft_version=1.21.8

tweakeroo_sr=1.21.8-0.25.5
litematica_sr=1.21.8-0.23.7
malilib_sr=1.21.8-0.25.7
minihud_sr=1.21.8-0.36.7
